server:
  port: 8080
spring:
  profiles:
    active: test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 1024MB
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 500ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: error